# 事务失效问题

## 1.事务失效问题

虽然解决了并发安全问题，但其实我们的改造却埋下了另一个隐患。一起测试一下。

我们在领券业务的最后故意抛出一个异常：

![img](https://b11et3un53m.feishu.cn/space/api/box/stream/download/asynccode/?code=NjNjNDk2MDIwNGQ4ZjdmZjk4MmFjZmI5NzVhY2QyYmZfYWt5aEhaOFdjcVl1YnhXZmNFeGJjTDU5dk9uZ0Z2RzBfVG9rZW46QTRvWGJuQ2lVb2ZuMmd4bGFib2NsT3FubllmXzE2OTA3MjA0OTg6MTY5MDcyNDA5OF9WNA)

经过测试，发现虽然抛出了异常，但是库存、用户券都没有回滚！事务失效了！

### 1.1.分析原因

事务失效的原因有很多，接下来我们就逐一分析一些常见的原因：

#### 1.1.1.事务方法非public修饰

由于Spring的事务是基于AOP的方式结合动态代理来实现的。因此事务方法一定要是public的，这样才能便于被Spring做事务的代理和增强。也就是说这里事务失效是因为该方法**并没有在当前类的代理类中创建其代理方法**相当于就是调用了一个类中的普通方法。

而且，在Spring内部也会有一个 `org.springframework.transaction.interceptor.AbstractFallbackTransactionAttributeSource`类，去检查事务方法的修饰符：

```Java
@Nullable
 protected TransactionAttribute computeTransactionAttribute(
  Method method, @Nullable Class<?> targetClass) {
   // Don't allow non-public methods, as configured.
   if (allowPublicMethodsOnly() && 
  !Modifier.isPublic(method.getModifiers())) {
      return null;
   }

    // ... 略

   return null;
 }
```

所以，事务方法一定要被public修饰！

#### 1.1.2.非事务方法调用事务方法

有这样一段代码：

```Java
@Service
public class OrderService {
    
    public void createOrder(){
        // ... 准备订单数据
        
        // 生成订单并扣减库存
        insertOrderAndReduceStock();
    }
    
    @Transactional
    public void insertOrderAndReduceStock(){
        // 生成订单
        insertOrder();
        // 扣减库存
        reduceStock();
    }
}
```

可以看到，`insertOrderAndReduceStock`方法是一个事务方法，肯定会被Spring事务管理。Spring会给`OrderService`类生成一个动态代理对象，对`insertOrderAndReduceStock`方法做增加，实现事务效果。

但是现在`createOrder`方法是一个非事务方法，在其中调用了`insertOrderAndReduceStock`方法，这个调用其实隐含了一个`this.`的前缀。也就是说，这里相当于是直接调用原始的OrderService中的普通方法，而非被Spring代理对象的代理方法。那事务肯定就失效了！

#### 1.1.3.事务方法的异常被捕获了

示例：

```Java
 @Service
 public class OrderService {

    @Transactional
    public void createOrder(){
        // ... 准备订单数据
        // 生成订单
        insertOrder();
        // 扣减库存
        reduceStock();
    }

    private void reduceStock() {
        try {
            // ...扣库存
        } catch (Exception e) {
            // 处理异常
        }
    }

 }
```

在这段代码中，reduceStock方法内部直接捕获了Exception类型的异常，也就是说方法执行过程中即便出现了异常也不会向外抛出。

而Spring的事务管理就是要感知业务方法的异常，当捕获到异常后才会回滚事务。

现在事务被捕获，就会导致Spring无法感知事务异常，自然不会回滚，事务就失效了。

#### 1.1.4.事务异常类型不对

示例代码：

```Java
@Service
 public class OrderService {

    @Transactional(rollbackFor = RuntimeException.class)
    public void createOrder() throws IOException {
        // ... 准备订单数据
        
        // 生成订单
        insertOrder();
        // 扣减库存
        reduceStock();

        throw new IOException();
    }
 }
```

Spring的事务管理默认感知的异常类型是`RuntimeException`，当事务方法内部抛出了一个`IOException`时，不会被Spring捕获，因此就不会触发事务回滚，事务就失效了。

因此，当我们的业务中会抛出RuntimeException以外的异常时，应该通过`@Transactional`注解中的`rollbackFor`属性来指定异常类型：

```Java
@Transactional(rollbackFor = Exception.class)
```

#### 1.1.5.事务传播行为不对

示例代码：

```Java
@Service
 public class OrderService {
    @Transactional
    public void createOrder(){
        // 生成订单
        insertOrder();
        // 扣减库存
        reduceStock();
        throw new RuntimeException("业务异常");
    }
    @Transactional
    public void insertOrder() {
    }
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void reduceStock() {
    }
 }
```

在示例代码中，事务的入口是`createOrder()`方法，会开启一个事务，可以成为外部事务。在createOrder()方法内部又调用了`insertOrder()`方法和`reduceStock()`方法。这两个都是事务方法。

不过，`reduceStock()`方法的事务传播行为是`REQUIRES_NEW`，这会导致在进入`reduceStock()`方法时会创建一个新的事务，可以成为子事务。`insertOrder()`则是默认，因此会与`createOrder()`合并事务。

因此，当`createOrder`方法最后抛出异常时，只会导致`insertOrder`方法回滚，而不会导致`reduceStock`方法回滚，因为`reduceStock`是一个独立事务。

所以，一定要慎用传播行为，注意外部事务与内部事务之间的关系。

#### 1.1.6.没有被Spring管理

示例代码：

```Java
//  @Service
 public class OrderService {
    @Transactional
    public void createOrder(){
        // 生成订单
        insertOrder();
        // 扣减库存
        reduceStock();
        throw new RuntimeException("业务异常");
    }
    @Transactional
    public void insertOrder() {
    }
    @Transactional
    public void reduceStock() {
    }
 }
```

这个示例属于比较低级的错误，`OrderService`类没有添加`@Service`注解，因此就没有被Spring管理。你在方法上添加的`@Transactional`注解根本不会有人帮你动态代理，事务自然失效。

当然，有同学会说，我不会犯这么低级的错误。这可不一定，有的时候你没有忘了加`@Service`注解，但是你在获取某个对象的时候，可能并不是获取的Spring管理的对象，有可能是其它方式创建的。这同样会导致事务失效。

### 1.2.解决方案

结合上节课的分析，大家应该能发现我们的事务失效的原因是什么了。

为了控制事务边界，我们改变了事务注解标记的位置，这就导致了**非事务方法调用了事务方法**。

怎么办？难道再把注解移回去？

这显然不合适，因为移回去就会导致并发安全问题。我们陷入了两难境地。

那么，有没有办法让这个事务再次生效呢？

答案是有的，既然事务失效的原因是方法内部调用走的是this，而不是代理对象。那我们只要**想办法获取代理对象**不就可以了嘛。

这里，我们可以借助AspectJ来实现。

1）引入AspectJ依赖：

```XML
<!--aspecj-->
<dependency>
    <groupId>org.aspectj</groupId>
    <artifactId>aspectjweaver</artifactId>
</dependency>
```

2）暴露代理对象

在启动类上添加注解，暴露代理对象：

![img](https://b11et3un53m.feishu.cn/space/api/box/stream/download/asynccode/?code=OWZmNjY5MGUzZTAxOTJkNWQ0N2JiZGJlNGQ2NGY0ZGVfcDR2ZTd4aTd6VTlQVHNzVFoxNXF0SUtkWDI5bVBPTFBfVG9rZW46RHV3UWJZeDJ5b09rYUN4ajZqWWNucnBHbjVnXzE2OTA3MjA0OTk6MTY5MDcyNDA5OV9WNA)

3）使用代理对象

最后，改造领取优惠券的代码，获取代理对象来调用事务方法：

![img](https://b11et3un53m.feishu.cn/space/api/box/stream/download/asynccode/?code=MmY5ZTA1MzMxYmYyYWRkNWJiMDMwMTYxYjM1MjEyM2RfcU1YTFRlUWU4bFlwc3ZVcnFTTnZOTlNBTTloMTE4WkJfVG9rZW46UEtYR2JWNjBqb1haV1Z4bDdKNWNXa3dBbldjXzE2OTA3MjA0OTk6MTY5MDcyNDA5OV9WNA)

问题解决。